import urllib.request
import json
import re

url = "https://api.github.com/repos/k2-fsa/sherpa-onnx/releases/tags/tts-models"
print("Fetching releases from sherpa-onnx...")
req = urllib.request.Request(url)
with urllib.request.urlopen(req) as resp:
    data = json.loads(resp.read())

voices = []

for asset in data.get("assets", []):
    name = asset["name"]
    # We want standard models, ignore -int8 and -fp16 versions.
    if name.startswith("vits-piper-") and name.endswith(".tar.bz2") and "-int8" not in name and "-fp16" not in name:
        # e.g. vits-piper-en_US-amy-low.tar.bz2
        match = re.match(r"vits-piper-([^-]+)-(.*)\.tar\.bz2", name)
        if match:
            lang = match.group(1)
            speaker_variant = match.group(2)
            voice_id = f"{lang}-{speaker_variant}"
            display_name = f"{speaker_variant.replace('_', ' ').replace('-', ' ').title()} — {lang}"
            
            # extract inner model name:
            # Usually it's the id + ".onnx" as defined in Piper.
            model_file = f"{voice_id}.onnx"
            
            voices.append({
                "name": voice_id,
                "display": display_name,
                "id": voice_id,
                "archive": name,
                "model": model_file
            })

# Sort voices, putting english first
def sort_key(v):
    is_en = v['name'].startswith('en_')
    return (not is_en, v['name'])

voices.sort(key=sort_key)

go_file_content = """package main

// Auto-generated by scripts/generate_voices.py
// DO NOT EDIT

var voices = []voiceEntry{
"""

for v in voices:
    go_file_content += f"""\t{{
\t\tName:        "{v['name']}",
\t\tDisplayName: "{v['display']}",
\t\tID:          "{v['id']}",
\t\tarchive:     "{v['archive']}",
\t\tmodelFile:   "{v['model']}",
\t}},
"""

go_file_content += "}\n"

# Write to the parent directory if running from scripts/, otherwise in current directory if running from piper_tts.
import os
out_path = "voices.go" if os.path.basename(os.getcwd()) == "piper_tts" else "../voices.go"
with open(out_path, "w") as f:
    f.write(go_file_content)

print(f"Generated voices.go with {len(voices)} voices.")
