import urllib.request
import json
import os

url = "https://huggingface.co/api/models/hexgrad/Kokoro-82M/tree/main/voices"
print("Fetching Kokoro voices from HuggingFace...")
req = urllib.request.Request(url)
with urllib.request.urlopen(req) as resp:
    data = json.loads(resp.read())

voices = []

# Filter for .pt files which represent the voices
for item in data:
    path = item.get("path", "")
    if path.endswith(".pt"):
        voice_id = path.split("/")[-1].replace(".pt", "")
        # First letter of voice_id maps to language
        # a: American English, b: British English, j: Japanese, z: Mandarin Chinese, e: Spanish, f: French, h: Hindi, i: Italian, p: Portuguese
        lang_codes = {
            'a': 'American English',
            'b': 'British English',
            'j': 'Japanese',
            'z': 'Mandarin Chinese',
            'e': 'Spanish',
            'f': 'French',
            'h': 'Hindi',
            'i': 'Italian',
            'p': 'Brazilian Portuguese',
        }
        
        # Determine gender based on second letter
        # f: Female, m: Male
        gender_codes = {
            'f': 'Female',
            'm': 'Male',
        }

        lang_prefix = voice_id[0]
        gender_prefix = voice_id[1]
        
        lang_name = lang_codes.get(lang_prefix, "Unknown")
        gender_name = gender_codes.get(gender_prefix, "Unknown")
        
        # e.g., "af_bella" -> "Bella" -> "Bella"
        # some names are like "am_michael" -> "Michael"
        parts = voice_id.split("_", 1)
        name_part = parts[1].replace("_", " ").title() if len(parts) > 1 else voice_id.title()
        
        display_name = f"{lang_name} {gender_name} — {name_part}"
        
        voices.append({
            "name": voice_id,
            "display": display_name,
            "id": voice_id,
        })

# Sort alphabetically to match SID mapping in sherpa-onnx's voices.bin
voices.sort(key=lambda x: x["name"])

# Assign SID
for idx, v in enumerate(voices):
    v["sid"] = idx

go_file_content = """package main

// Auto-generated by scripts/generate_voices.py
// Fetched from HuggingFace: hexgrad/Kokoro-82M
// DO NOT EDIT

var kokoroVoices = []voiceEntry{
"""

for v in voices:
    go_file_content += f"""\t{{
\t\tName:        "{v['name']}",
\t\tDisplayName: "{v['display']}",
\t\tID:          "{v['id']}",
\t\tSID:         {v['sid']},
\t}},
"""

go_file_content += "}\n"

out_path = "voices.go" if os.path.basename(os.getcwd()) == "kokoro_tts" else "../voices.go"
with open(out_path, "w") as f:
    f.write(go_file_content)

print(f"Generated {out_path} with {len(voices)} voices.")
